---
name: pre-commit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:

  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install pre-commit
        run: pip install pre-commit

      - name: run pre-commit(trailing-whitespace)
        run: |
          pre-commit run 'trailing-whitespace' \
            --show-diff-on-failure \
            --color=always \
            --all-files

      - name: run pre-commit(end-of-file-fixer)
        run: |
          pre-commit run 'end-of-file-fixer' \
            --show-diff-on-failure \
            --color=always \
            --all-files

      - name: run pre-commit(check-yaml)
        run: |
          pre-commit run 'check-yaml' \
            --show-diff-on-failure \
            --color=always \
            --all-files

      - name: run pre-commit(check-added-large-files)
        run: |
          pre-commit run 'check-added-large-files' \
            --show-diff-on-failure \
            --color=always \
            --all-files

      - name: run pre-commit(mixed-line-ending)
        run: |
          pre-commit run 'mixed-line-ending' \
            --show-diff-on-failure \
            --color=always \
            --all-files
